version: '3.8'

services:
  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - n8n-network

  # n8n:
  #   image: n8nio/n8n:latest
  #   container_name: n8n
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   user: "1000:1000"
  #   environment:
  #     DB_TYPE: postgresdb
  #     DB_POSTGRESDB_HOST: postgres
  #     DB_POSTGRESDB_PORT: 5432
  #     DB_POSTGRESDB_USER: ${POSTGRES_USER}
  #     DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
  #     DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
  #     N8N_EDITOR_BASE_URL: https://onlyanalyst.ru
  #     N8N_PROTOCOL: https
  #     N8N_HOST: onlyanalyst.ru
  #     N8N_PORT: 5678
  #     WEBHOOK_URL: https://onlyanalyst.ru
  #     GENERIC_TIMEZONE: Europe/Moscow
  #   volumes:
  #     - ./n8n:/home/node/.n8n
  #   ports:
  #     - "5678:5678"
  #   networks:
  #     - n8n-network

  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    restart: unless-stopped
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
    volumes:
      - jupyter_data:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - n8n-network
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

volumes:
 # postgres_data:
  jupyter_data:

networks:
  n8n-network:
    driver: bridge
